# .streamlit/secrets.toml

[database]
host = "ep-twilight-sky-adbwe9m5-pooler.c-2.us-east-1.aws.neon.tech"
port = 5432
dbname = "neondb"
user = "neondb_owner"
password = "npg_YNkW3fwKFzX7" 
# A senha que estava no lugar dos asteriscos

# >>>>> NOVA SEÇÃO <<<<<
[cloudinary]
cloud_name = "dgaqbdorp"
api_key = "625724337699677"
api_secret = "z9fxaonpnNfhWM01JghOvhlJvf4"
